name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pip-dependencies:
          - [dev]
          - [dev, numpy]
        include:
          - os: ubuntu-latest
            pip-dependencies: [dev, numpy, cffi]
            build-steps: |
              sudo apt-get update && sudo apt-get install -y build-essential g++ libssl-dev libtbb-dev python3-dev
              cd nphash
              python build.py
              ls -lh _npblake2bffi.* _npblake3ffi.* _npsha256ffi.*
              cd ..
              python -m pip install .

          - os: macos-latest
            pip-dependencies: [dev, numpy, cffi]
            build-steps: |
              brew install libomp openssl tbb
              cd nphash
              python build.py
              ls -lh _npblake2bffi.* _npblake3ffi.* _npsha256ffi.*
              cd ..
              python -m pip install .

          - os: windows-latest
            pip-dependencies: [dev, numpy, cffi]
            build-steps: |
              curl -L -o tbb.zip https://github.com/uxlfoundation/oneTBB/releases/download/v2022.1.0/oneapi-tbb-2022.1.0-win.zip
              7z x tbb.zip -otbb
              set "INCLUDE=%CD%\tbb\oneapi-tbb-2022.1.0\include;%INCLUDE%"
              set "LIB=%CD%\tbb\oneapi-tbb-2022.1.0\lib\intel64\vc14;%LIB%"
              choco install openssl --no-progress -y
              cd nphash
              python build.py
              dir _npblake2bffi.* _npblake3ffi.* _npsha256ffi.*
              cd ..
              python -m pip install .

    name: test_${{ matrix.os }}_${{ join(matrix.pip-dependencies, '_') }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ matrix.os == 'ubuntu-latest' && '~/.cache/pip' 
            || matrix.os == 'macos-latest' && '~/Library/Caches/pip'
            || matrix.os == 'windows-latest' && '~\\AppData\\Local\\pip\\Cache'
            || '' }}
          key: ${{ matrix.os }}-pip-${{ join(matrix.pip-dependencies, '_') }}
          restore-keys: |
            ${{ matrix.os }}-pip-${{ join(matrix.pip-dependencies, '_') }}

      - name: Install Python dependencies and library
        run: python -m pip install .[${{ join(matrix.pip-dependencies, ',') }}]

      - name: Build/package steps (Windows)
        if: matrix.build-steps != '' && matrix.os == 'windows-latest'
        run: ${{ matrix.build-steps }}
        shell: cmd

      - name: Build/package steps (non-Windows)
        if: matrix.build-steps != '' && matrix.os != 'windows-latest'
        run: ${{ matrix.build-steps }}
        shell: bash

      - name: Setup tmate session (for interactive SSH debugging)
        if: matrix.os == 'windows-latest'
        uses: mxschmitt/action-tmate@v3

      - name: Run tests
        run: python -m unittest discover -s tests/ -v
