name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pip-dependencies:
          - [dev]
          - [dev, numpy]
        include:
          - os: ubuntu-latest
            pip-dependencies: [dev, numpy, cffi]
            build-steps: |
              sudo apt-get update && sudo apt-get install -y build-essential libssl-dev python3-dev g++ libtbb-dev
              cd nphash
              python build.py

          - os: ubuntu-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_notbb'
            build-steps: |
              sudo apt-get update && sudo apt-get install -y build-essential libssl-dev python3-dev
              cd nphash
              export NPBLAKE3_NO_TBB=1
              python build.py

          - os: ubuntu-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_nosimd'
            build-steps: |
              sudo apt-get update && sudo apt-get install -y build-essential libssl-dev python3-dev g++ libtbb-dev
              cd nphash
              export NPBLAKE3_NO_SIMD=1
              python build.py

          - os: ubuntu-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_noasm'
            build-steps: |
              sudo apt-get update && sudo apt-get install -y build-essential libssl-dev python3-dev g++ libtbb-dev
              cd nphash
              export NPBLAKE3_NO_ASM=1
              python build.py

          - os: ubuntu-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_nobmh'
            build-steps: |
              sudo apt-get update && sudo apt-get install -y build-essential libssl-dev python3-dev g++ libtbb-dev
              cd nphash
              export BYTESEARCH_NO_BMH=1
              python build.py

          - os: macos-latest
            pip-dependencies: [dev, numpy, cffi]
            build-steps: |
              brew install libomp openssl tbb
              cd nphash
              python build.py

          - os: macos-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_notbb'
            build-steps: |
              brew install libomp openssl
              cd nphash
              export NPBLAKE3_NO_TBB=1
              python build.py

          - os: macos-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_nosimd'
            build-steps: |
              brew install libomp openssl tbb
              cd nphash
              export NPBLAKE3_NO_SIMD=1
              python build.py

          - os: windows-latest
            pip-dependencies: [dev, numpy, cffi]
            build-steps: |
              @echo on
              if not exist vcpkg (
                git clone https://github.com/microsoft/vcpkg.git
                call .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
                call .\vcpkg\vcpkg.exe install tbb:x64-windows
              )
              copy .\vcpkg\installed\x64-windows\bin\tbb*.dll nphash\
              set INCLUDE=%CD%\vcpkg\installed\x64-windows\include;%INCLUDE%
              set LIB=%CD%\vcpkg\installed\x64-windows\lib;%LIB%
              choco install openssl visualstudio2022buildtools --no-progress -y
              call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              cd nphash
              python build.py

          - os: windows-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_notbb'
            build-steps: |
              @echo on
              choco install openssl visualstudio2022buildtools --no-progress -y
              call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              cd nphash
              set NPBLAKE3_NO_TBB=1
              python build.py

          - os: windows-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_nosimd'
            build-steps: |
              @echo on
              if not exist vcpkg (
                git clone https://github.com/microsoft/vcpkg.git
                call .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
                call .\vcpkg\vcpkg.exe install tbb:x64-windows
              )
              copy .\vcpkg\installed\x64-windows\bin\tbb*.dll nphash\
              set INCLUDE=%CD%\vcpkg\installed\x64-windows\include;%INCLUDE%
              set LIB=%CD%\vcpkg\installed\x64-windows\lib;%LIB%
              choco install openssl visualstudio2022buildtools --no-progress -y
              call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              cd nphash
              set NPBLAKE3_NO_SIMD=1
              python build.py

          - os: windows-latest
            pip-dependencies: [dev, numpy, cffi]
            postfix: '_noasm'
            build-steps: |
              @echo on
              if not exist vcpkg (
                git clone https://github.com/microsoft/vcpkg.git
                call .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
                call .\vcpkg\vcpkg.exe install tbb:x64-windows
              )
              copy .\vcpkg\installed\x64-windows\bin\tbb*.dll nphash\
              set INCLUDE=%CD%\vcpkg\installed\x64-windows\include;%INCLUDE%
              set LIB=%CD%\vcpkg\installed\x64-windows\lib;%LIB%
              choco install openssl visualstudio2022buildtools --no-progress -y
              call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              cd nphash
              set NPBLAKE3_NO_ASM=1
              python build.py

    name: test_${{ matrix.os }}_${{ join(matrix.pip-dependencies, '_') }}${{ matrix.postfix || '' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ matrix.os == 'ubuntu-latest' && '~/.cache/pip' 
            || matrix.os == 'macos-latest' && '~/Library/Caches/pip'
            || matrix.os == 'windows-latest' && '~\\AppData\\Local\\pip\\Cache'
            || '' }}
          key: ${{ matrix.os }}-pip-${{ join(matrix.pip-dependencies, '_') }}
          restore-keys: |
            ${{ matrix.os }}-pip-${{ join(matrix.pip-dependencies, '_') }}

      - name: Cache vcpkg and TBB (Windows)
        if: matrix.build-steps != '' && matrix.os == 'windows-latest' && matrix.postfix != '_notbb'
        uses: actions/cache@v4
        with:
          path: vcpkg
          key: vcpkg_windows-latest

      - name: Install Python dependencies and library
        run: python -m pip install -e .[${{ join(matrix.pip-dependencies, ',') }}]

      - name: Build/package steps (Windows)
        if: matrix.build-steps != '' && matrix.os == 'windows-latest'
        run: ${{ matrix.build-steps }}
        shell: cmd

      - name: Build/package steps (Linux/macOS)
        if: matrix.build-steps != '' && matrix.os != 'windows-latest'
        run: ${{ matrix.build-steps }}
        shell: bash

#      - name: Setup tmate session (for interactive SSH debugging)
#        if: matrix.os == 'windows-latest'
#        uses: mxschmitt/action-tmate@v3

      - name: Run tests
        run: python -m unittest discover -s tests/ -v

      - name: Assert C module existence and importability
        if: matrix.build-steps != ''
        run: | 
          ls -lh nphash/_bytesearchffi.*.* nphash/_npblake2bffi.*.* nphash/_npblake3ffi.*.* nphash/_npsha256ffi.*.*
          python -c "from vernamveil._imports import _HAS_C_MODULE; assert _HAS_C_MODULE; print('The C module is importable')"
        shell: bash
